import type { Program } from '@/types';

export const programs: Program[] = [
  // Akademik
  {
    id: 'prog-calistung',
    slug: 'calistung',
    category: 'akademik',
    name: 'Calistung Balita & Anak',
    description: 'Membaca, menulis, dan berhitung dengan metode menyenangkan.',
    icon: 'PencilRuler',
    priceFrom: 169000,
    sessionDurationMinutes: 60,
    subjects: ['Membaca', 'Menulis', 'Berhitung'],
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 'prog-sd',
    slug: 'sd',
    category: 'akademik',
    name: 'Les SD (Kelas 1–6)',
    description: 'Matematika, IPA, Bahasa Indonesia, Bahasa Inggris.',
    icon: 'BookOpen',
    priceFrom: 199000,
    sessionDurationMinutes: 90,
    subjects: ['Matematika', 'IPA', 'Bahasa Indonesia', 'Bahasa Inggris'],
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 'prog-smp',
    slug: 'smp',
    category: 'akademik',
    name: 'Les SMP (Kelas 7–9)',
    description: 'Matematika, IPA, Bahasa Indonesia, Bahasa Inggris.',
    icon: 'BookMarked',
    priceFrom: 235000,
    sessionDurationMinutes: 90,
    subjects: ['Matematika', 'IPA', 'Bahasa Indonesia', 'Bahasa Inggris'],
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 'prog-sma',
    slug: 'sma',
    category: 'akademik',
    name: 'Les SMA (Kelas 10–12)',
    description: 'Matematika, Fisika, Kimia, Biologi, Bahasa, Akuntansi.',
    icon: 'GraduationCap',
    priceFrom: 285000,
    sessionDurationMinutes: 90,
    subjects: ['Matematika', 'Fisika', 'Kimia', 'Biologi', 'Bahasa Inggris', 'Akuntansi'],
    sortOrder: 4,
    isActive: true,
  },
  // Persiapan khusus
  {
    id: 'prog-persiapan-snbt',
    slug: 'snbt-utbk',
    category: 'persiapan-khusus',
    name: 'Persiapan SNBT/UTBK',
    description: 'Strategi & latihan intensif untuk tembus PTN impian.',
    icon: 'Crosshair',
    priceFrom: 245000,
    sessionDurationMinutes: 90,
    subjects: ['TPS', 'Literasi', 'Penalaran Matematika', 'Bahasa Inggris'],
    sortOrder: 5,
    isActive: true,
  },
  {
    id: 'prog-persiapan-kedinasan',
    slug: 'kedinasan',
    category: 'persiapan-khusus',
    name: 'Persiapan Kedinasan (STAN, STIS)',
    description: 'Drill soal TKD & TIU + materi khusus tiap sekolah dinas.',
    icon: 'ShieldCheck',
    priceFrom: 245000,
    sessionDurationMinutes: 90,
    subjects: ['TKD', 'TIU', 'TWK'],
    sortOrder: 6,
    isActive: true,
  },
  {
    id: 'prog-olimpiade',
    slug: 'olimpiade',
    category: 'persiapan-khusus',
    name: 'Persiapan Olimpiade',
    description: 'Pembinaan untuk OSN dan kompetisi tingkat nasional/internasional.',
    icon: 'Medal',
    priceFrom: 245000,
    sessionDurationMinutes: 90,
    subjects: ['Matematika', 'Fisika', 'Kimia', 'Biologi', 'Informatika'],
    sortOrder: 7,
    isActive: true,
  },
  // Skill & Bahasa
  {
    id: 'prog-english',
    slug: 'english',
    category: 'skill',
    name: 'English (Beginner – Advanced)',
    description: 'Speaking, grammar, dan conversation untuk segala level.',
    icon: 'Globe2',
    priceFrom: 199000,
    sessionDurationMinutes: 60,
    subjects: ['Speaking', 'Grammar', 'Writing'],
    sortOrder: 8,
    isActive: true,
  },
  {
    id: 'prog-ielts',
    slug: 'ielts-toefl',
    category: 'skill',
    name: 'IELTS / TOEFL',
    description: 'Persiapan tes untuk studi & karir internasional.',
    icon: 'Plane',
    priceFrom: 199000,
    sessionDurationMinutes: 60,
    subjects: ['Listening', 'Reading', 'Writing', 'Speaking'],
    sortOrder: 9,
    isActive: true,
  },
  {
    id: 'prog-mandarin',
    slug: 'mandarin',
    category: 'skill',
    name: 'Bahasa Mandarin',
    description: 'Pinyin, hanzi, dan percakapan dari nol hingga lancar.',
    icon: 'Languages',
    priceFrom: 199000,
    sessionDurationMinutes: 60,
    subjects: ['Pinyin', 'Hanzi', 'Conversation'],
    sortOrder: 10,
    isActive: true,
  },
  {
    id: 'prog-jepang',
    slug: 'jepang',
    category: 'skill',
    name: 'Bahasa Jepang',
    description: 'Hiragana, katakana, kanji, hingga JLPT.',
    icon: 'Languages',
    priceFrom: 199000,
    sessionDurationMinutes: 60,
    subjects: ['Hiragana', 'Katakana', 'Kanji', 'JLPT'],
    sortOrder: 11,
    isActive: true,
  },
  {
    id: 'prog-korea',
    slug: 'korea',
    category: 'skill',
    name: 'Bahasa Korea',
    description: 'Hangul, percakapan, dan persiapan TOPIK.',
    icon: 'Languages',
    priceFrom: 199000,
    sessionDurationMinutes: 60,
    subjects: ['Hangul', 'Conversation', 'TOPIK'],
    sortOrder: 12,
    isActive: true,
  },
  // Musik
  {
    id: 'prog-piano',
    slug: 'piano',
    category: 'musik',
    name: 'Piano',
    description: 'Klasik, pop, hingga kontemporer untuk segala usia.',
    icon: 'Piano',
    priceFrom: 240000,
    sessionDurationMinutes: 45,
    subjects: ['Klasik', 'Pop', 'Kontemporer'],
    sortOrder: 13,
    isActive: true,
  },
  {
    id: 'prog-gitar',
    slug: 'gitar',
    category: 'musik',
    name: 'Gitar',
    description: 'Akustik & elektrik, chord, fingerstyle, hingga improvisasi.',
    icon: 'Guitar',
    priceFrom: 240000,
    sessionDurationMinutes: 45,
    subjects: ['Akustik', 'Elektrik', 'Fingerstyle'],
    sortOrder: 14,
    isActive: true,
  },
  {
    id: 'prog-biola',
    slug: 'biola',
    category: 'musik',
    name: 'Biola',
    description: 'Teknik dasar hingga repertoar klasik.',
    icon: 'Music2',
    priceFrom: 240000,
    sessionDurationMinutes: 45,
    subjects: ['Teknik Dasar', 'Repertoar', 'Solfeggio'],
    sortOrder: 15,
    isActive: true,
  },
  {
    id: 'prog-vokal',
    slug: 'vokal',
    category: 'musik',
    name: 'Vokal',
    description: 'Pernapasan, pitch, dan teknik panggung.',
    icon: 'Mic',
    priceFrom: 240000,
    sessionDurationMinutes: 45,
    subjects: ['Pernapasan', 'Pitch Control', 'Performance'],
    sortOrder: 16,
    isActive: true,
  },
];

export const programCategoryLabel: Record<Program['category'], string> = {
  akademik: 'Akademik',
  'persiapan-khusus': 'Persiapan Khusus',
  skill: 'Skill & Bahasa',
  musik: 'Musik',
};
