import type { Tutor } from '@/types';

/**
 * Tutor data placeholder untuk MVP.
 * Foto dummy via randomuser.me. Ganti dengan foto profesional asli sebelum production.
 */
export const tutors: Tutor[] = [
  {
    id: 't-1',
    slug: 'kak-rina',
    fullName: 'Kak Rina',
    photoUrl: 'https://randomuser.me/api/portraits/women/68.jpg',
    subjects: ['Matematika SD', 'Matematika SMP'],
    experienceYears: 5,
    shortBio: 'Lulusan Pendidikan Matematika UPI. Sabar dan komunikatif dengan anak.',
    badges: ['Math Specialist', 'SD & SMP'],
    isFeatured: true,
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 't-2',
    slug: 'kak-bayu',
    fullName: 'Kak Bayu',
    photoUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    subjects: ['Fisika SMA', 'Matematika SMA', 'Persiapan SNBT'],
    experienceYears: 7,
    shortBio: 'Magister Fisika ITB. Spesialis persiapan SNBT/UTBK saintek.',
    badges: ['SNBT Expert', 'Fisika'],
    isFeatured: true,
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 't-3',
    slug: 'kak-sasha',
    fullName: 'Kak Sasha',
    photoUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
    subjects: ['Bahasa Inggris', 'IELTS', 'TOEFL'],
    experienceYears: 6,
    shortBio: 'IELTS overall 8.0. Membimbing puluhan siswa lanjut studi ke luar negeri.',
    badges: ['IELTS 8.0', 'Native-like'],
    isFeatured: true,
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 't-4',
    slug: 'kak-dimas',
    fullName: 'Kak Dimas',
    photoUrl: 'https://randomuser.me/api/portraits/men/45.jpg',
    subjects: ['Kimia SMA', 'Biologi SMA', 'Persiapan SNBT'],
    experienceYears: 4,
    shortBio: 'Pendidikan Kimia UPI. Membuat hafalan jadi pemahaman.',
    badges: ['Saintek'],
    isFeatured: false,
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 't-5',
    slug: 'kak-melinda',
    fullName: 'Kak Melinda',
    photoUrl: 'https://randomuser.me/api/portraits/women/22.jpg',
    subjects: ['Calistung', 'SD Kelas 1 sampai 3'],
    experienceYears: 3,
    shortBio: 'PG-PAUD Universitas Pendidikan Indonesia. Spesialis early learning.',
    badges: ['Early Learning'],
    isFeatured: false,
    sortOrder: 5,
    isActive: true,
  },
  {
    id: 't-6',
    slug: 'kak-rio',
    fullName: 'Kak Rio',
    photoUrl: 'https://randomuser.me/api/portraits/men/77.jpg',
    subjects: ['Piano', 'Vokal'],
    experienceYears: 8,
    shortBio: 'Lulusan ISI Yogyakarta jurusan Musik. Pengalaman mengajar 8 tahun.',
    badges: ['Musik'],
    isFeatured: true,
    sortOrder: 6,
    isActive: true,
  },
  {
    id: 't-7',
    slug: 'kak-yumi',
    fullName: 'Kak Yumi',
    photoUrl: 'https://randomuser.me/api/portraits/women/55.jpg',
    subjects: ['Bahasa Jepang', 'Bahasa Korea'],
    experienceYears: 5,
    shortBio: 'JLPT N2 & TOPIK Level 5. Pengajar bahasa Jepang & Korea.',
    badges: ['Bahasa Asing'],
    isFeatured: false,
    sortOrder: 7,
    isActive: true,
  },
  {
    id: 't-8',
    slug: 'kak-arif',
    fullName: 'Kak Arif',
    photoUrl: 'https://randomuser.me/api/portraits/men/52.jpg',
    subjects: ['Akuntansi SMA', 'Ekonomi SMA'],
    experienceYears: 6,
    shortBio: 'Akuntansi Unpad, profesional finance dengan passion mengajar.',
    badges: ['SMA IPS'],
    isFeatured: false,
    sortOrder: 8,
    isActive: true,
  },
];
