import type { University } from '@/types';

/**
 * Alma mater of Teman Tutor teaching staff. Names follow the client-supplied
 * logo filenames verbatim (REVISI 3, 2026-07-25).
 */
export const universities: University[] = [
  {
    id: 'univ-itb',
    name: 'Institut Teknologi Bandung (ITB)',
    logoUrl: '/images/universitas/institut-teknologi-bandung-itb.webp',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 'univ-ui',
    name: 'Universitas Indonesia (UI)',
    logoUrl: '/images/universitas/universitas-indonesia-ui.webp',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 'univ-ugm',
    name: 'Universitas Gajah Mada (UGM)',
    logoUrl: '/images/universitas/universitas-gajah-mada-ugm.webp',
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 'univ-unpad',
    name: 'Universitas Padjajaran (UNPAD)',
    logoUrl: '/images/universitas/universitas-padjajaran-unpad.webp',
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 'univ-upi',
    name: 'Universitas Pendidikan Indonesia (UPI)',
    logoUrl: '/images/universitas/universitas-pendidikan-indonesia-upi.webp',
    sortOrder: 5,
    isActive: true,
  },
  {
    id: 'univ-unair',
    name: 'Universitas Airlangga (UNAIR)',
    logoUrl: '/images/universitas/universitas-airlangga-unair.webp',
    sortOrder: 6,
    isActive: true,
  },
  {
    id: 'univ-unj',
    name: 'Universitas Negeri Jakarta (UNJ)',
    logoUrl: '/images/universitas/universitas-negeri-jakarta-unj.webp',
    sortOrder: 7,
    isActive: true,
  },
  {
    id: 'univ-binus',
    name: 'Bina Nusantara University (BINUS)',
    logoUrl: '/images/universitas/bina-nusantara-binus.webp',
    sortOrder: 8,
    isActive: true,
  },
  {
    id: 'univ-unpar',
    name: 'Universitas Katolik Parahyangan (UNPAR)',
    logoUrl: '/images/universitas/universitas-katolik-parahyangan-unpar.webp',
    sortOrder: 9,
    isActive: true,
  },
  {
    id: 'univ-uph',
    name: 'Universitas Pelita Harapan (UPH)',
    logoUrl: '/images/universitas/universitas-pelita-harapan-uph.webp',
    sortOrder: 10,
    isActive: true,
  },
  {
    id: 'univ-untar',
    name: 'Universitas Tarumanagara (UNTAR)',
    logoUrl: '/images/universitas/universitas-tarumanagara-untar.webp',
    sortOrder: 11,
    isActive: true,
  },
  {
    id: 'univ-trisakti',
    name: 'Universitas Trisakti',
    logoUrl: '/images/universitas/universitas-trisakti.webp',
    sortOrder: 12,
    isActive: true,
  },
  {
    id: 'univ-ithb',
    name: 'Institut Teknologi Harapan Bangsa (ITHB)',
    logoUrl: '/images/universitas/institut-teknologi-harapan-bangsa-ithb.webp',
    sortOrder: 13,
    isActive: true,
  },
  {
    id: 'univ-itenas',
    name: 'Institut Teknologi Nasional (ITENAS)',
    logoUrl: '/images/universitas/institut-teknologi-nasional-itenas.webp',
    sortOrder: 14,
    isActive: true,
  },
  {
    id: 'univ-maranatha',
    name: 'Universitas Kristen Maranatha',
    logoUrl: '/images/universitas/universitas-kristen-maranatha.webp',
    sortOrder: 15,
    isActive: true,
  },
  {
    id: 'univ-unpas',
    name: 'Universitas Pasundan (UNPAS)',
    logoUrl: '/images/universitas/universitas-pasundan-unpas.webp',
    sortOrder: 16,
    isActive: true,
  },
  {
    id: 'univ-widyatama',
    name: 'Universitas Widyatama',
    logoUrl: '/images/universitas/universitas-widyatama.webp',
    sortOrder: 17,
    isActive: true,
  },
  {
    id: 'univ-unikom',
    name: 'Universitas Komputer Indonesia (UNIKOM)',
    logoUrl: '/images/universitas/universitas-komputer-indonesia-unikom.webp',
    sortOrder: 18,
    isActive: true,
  },
  {
    id: 'univ-mercu-buana',
    name: 'Universitas Mercu Buana',
    logoUrl: '/images/universitas/universitas-mercu-buana.webp',
    sortOrder: 19,
    isActive: true,
  },
  {
    id: 'univ-unas',
    name: 'Universitas Nasional (UNAS)',
    logoUrl: '/images/universitas/universitas-nasional-unas.webp',
    sortOrder: 20,
    isActive: true,
  },
  {
    id: 'univ-unsada',
    name: 'Universitas Darma Persada (UNSADA)',
    logoUrl: '/images/universitas/universitas-darma-persada-unsada.webp',
    sortOrder: 21,
    isActive: true,
  },
  {
    id: 'univ-stimb',
    name: 'Sekolah Tinggi Musik Bandung (STiMB)',
    logoUrl: '/images/universitas/sekolah-tinggi-musik-bandung-stimb.webp',
    sortOrder: 22,
    isActive: true,
  },
  {
    id: 'univ-aba',
    name: 'Akademi Bahasa Asing (ABA)',
    logoUrl: '/images/universitas/akademi-bahasa-asing-aba.webp',
    sortOrder: 23,
    isActive: true,
  },
];
